Repository ucsb-cs156-f22/f22-7pm-courses, pull requests merged in 2022-11, with the labels that each got.

#6 Changed 'Example' brand to say UCSB Courses Search f22-7PM-2
  frontend/src/main/components/Nav/AppNavbar.js
Labels: 5, f22-7pm-2

#16 MN & EE - Implement 15 character limit for Personal Schedule names
  frontend/src/main/components/PersonalSchedules/PersonalScheduleForm.js
  frontend/src/tests/components/PersonalSchedules/PersonalScheduleForm.test.js
  src/main/java/edu/ucsb/cs156/courses/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesController.java
  src/main/java/edu/ucsb/cs156/courses/errors/CharLimitExceededException.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesControllerTests.java
Labels: 10, f22-7pm-2

#13 A j footer source repo
  frontend/src/fixtures/systemInfoFixtures.js
  frontend/src/main/components/Nav/Footer.js
  frontend/src/main/layouts/BasicLayout/BasicLayout.js
  frontend/src/main/utils/systemInfo.js
  frontend/src/stories/layouts/BasicLayout/Footer.stories.js
  frontend/src/tests/components/Nav/Footer.test.js
  frontend/src/tests/utils/systemInfo.test.js
  src/main/java/edu/ucsb/cs156/courses/models/SystemInfo.java
  src/main/java/edu/ucsb/cs156/courses/services/SystemInfoServiceImpl.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/courses/controllers/SystemInfoControllerTests.java
Labels: f22-7pm-1, FIXME: Changes Requested

#15 MM&MK-SwapSearch
  .gitignore
  frontend/.gitignore
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/BasicCourseSearch/BasicCourseSearchIndexPage.js
  frontend/src/stories/pages/HomePage/frontend/src/CourseDescriptionIndexPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/BasicCourseSearch/BasicCourseSearchIndexPage.test.js
Labels: 10, f22-7pm-1

#28 Updated README storybook links
  README.md
Labels: 5, f22-7pm-2

#26 HY & AG - Personal schedule dropdown component
  frontend/src/fixtures/personalSchedulesFixtures.js
  frontend/src/main/components/PersonalSchedules/SinglePersonalScheduleDropdown.js
  frontend/src/stories/components/PersonalSchedules/SinglePersonalScheduleDropdown.stories.js
  frontend/src/tests/components/PersonalSchedules/SinglePersonalScheduleDropdown.test.js
Labels: 10, f22-7pm-2

#30 HY - PSCourse dropdown
  frontend/src/main/components/Courses/CourseForm.js
  frontend/src/main/pages/Courses/PSCourseCreatePage.js
  frontend/src/tests/components/Courses/CourseForm.test.js
  frontend/src/tests/pages/Courses/CoursesCreatePage.test.js
Labels: f22-7pm-2, STAFF: ready for review

#31 Change the color of navbar to UCSB blue
  .gitignore
  frontend/src/index.css
  frontend/src/main/components/Nav/AppNavbar.js
Labels: 5, f22-7pm-1, FIXME: Peer CR

#34 MM - Add Quarter.java and QuarterTests.java
  .gitignore
  src/main/java/edu/ucsb/cs156/courses/models/Quarter.java
  src/test/java/edu/ucsb/cs156/courses/models/QuarterTests.java
Labels: f22-7pm-1

#37 EE & MN - PersonalSectionsTable component + Storybook
  frontend/src/fixtures/personalSectionsFixtures.js
  frontend/src/main/components/PersonalSections/PersonalSectionsTable.js
  frontend/src/stories/components/PersonalSections/PersonalSectionsTable.stories.js
  frontend/src/tests/components/PersonalSections/PersonalSectionsTable.test.js
Labels: 10, f22-7pm-2

#40 CL and DC - BACKEND: Personal Schedule names should be unique when taken together with the quarter
  src/main/java/edu/ucsb/cs156/courses/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesController.java
  src/main/java/edu/ucsb/cs156/courses/errors/NameAndQuarterExistsException.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesControllerTests.java
Labels: 10, f22-7pm-2

#41 Add a New Column for Section Number to the Table
  .gitignore
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/main/components/SectionsTableBase.js
  frontend/src/main/utils/sectionUtils.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
  frontend/src/tests/utils/sectionUtils.test.js
Labels: f22-7pm-1, STAFF: ready for review
