Repository ucsb-cs156-f22/f22-7pm-courses, pull requests merged in 2022-12, with the labels that each got.

#51 Fixed mutation test for QuarterTests.java
  src/main/java/edu/ucsb/cs156/courses/models/Quarter.java
  src/test/java/edu/ucsb/cs156/courses/models/QuarterTests.java
Labels: f22-7pm-1, STAFF: ready for review

#47 AG & HY -Personal Schedule Edit Page Implementation
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesEditPage.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesEditPage.test.js
Labels: 10, f22-7pm-2

#54 MK&TK Implemented MongoDB query and controller for searching courses over time
  .gitignore
  src/main/java/edu/ucsb/cs156/courses/collections/ConvertedSectionCollection.java
  src/main/java/edu/ucsb/cs156/courses/controllers/HistoryCourseSearchController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/HistoryCourseSearchControllerTests.java
Labels: f22-7pm-1, INSTRUCTOR: assign pts

#53 DC - FRONTEND: Personal Schedule names should be unique when taken together with the quarter
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesCreatePage.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesCreatePage.test.js
Labels: 10, f22-7pm-2

#57 f22-7pm-1 JUN- NEW JOB(BACKEND): UPDATE SUBJECTS WITH QUARTER ONLY
  .DS_Store
  src/main/java/edu/ucsb/cs156/courses/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataJob.java
  src/main/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataJobFactoryQuarters.java
  src/main/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataJobQuarters.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBSubjectsService.java
  src/main/java/edu/ucsb/cs156/courses/services/jobs/JobService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/JobsControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataJobFactoryQuartersTests.java
  src/test/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataJobQuartersTests.java
Labels: f22-7pm-1, FIXME: Changes Requested, Merge Candidate: Needs QA deploy

#48 MN & EE - Add PersonalSectionsTable to PersonalScheduleDetailsPage
  frontend/src/fixtures/personalSectionsFixtures.js
  frontend/src/main/components/PersonalSections/PersonalSectionsTable.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesDetailsPage.js
  frontend/src/tests/components/PersonalSections/PersonalSectionsTable.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesDetailsPage.test.js
Labels: f22-7pm-2, STAFF: ready for review
